#!/bin/bash

if [ -d "$1" ]; then
  clear
  cd "$1" || exit
  python app.py
  cd -
  clear
  echo "$1 has run" 
elif [ -f "$1" ]; then
  clear
  python "$1"
  clear
 echo "$1 has run" 
elif [ -f "$1" ]; then
  clear
  source "$1"
  clear
  echo "$1 has run" 
else
  echo "No such file or directory: $1"
fi
